repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
  - repo: local
    hooks:
    -   id: content_yaml_autoformat
        name: content yaml autoformatting
        entry: tools/rewrite-content-yaml.py
        files: 'content/.*\.ya?ml'
        language: python
        additional_dependencies: ['PyYAML==6.0.1', 'ruamel.yaml==0.17.4']
    -   id: yaml_validation
        name: yaml schema validation
        entry: build-tools/github/validate-yaml
        pass_filenames: false # we do cross-file checking so true would not work
          #require_serial: true # TODO this should not matter
        files: 'content/.*'
        language: node
        additional_dependencies: ['pajv']
    -   id: yaml_cross_lang
        name: yaml cross lang validation
        entry: python tools/check-yaml-structure.py
        pass_filenames: false # we do cross-file checking so true would not work
          #require_serial: true # TODO this should not matter
        files: 'content/.*'
        language: python
        additional_dependencies: ['ruamel.yaml==0.17.4']
