#!/bin/bash
# Run all validation scripts.
# This script runs on GitHub in the PR build, NOT ON HEROKU. It can therefore not
# rely on the dependencies of the top-level package.json having been installed.
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

python content/yaml_to_lark_utils.py

if [[ "${1:-}" == "base" ]]; then
  $scriptdir/validate-python
  $scriptdir/validate-typescript
  $scriptdir/validate-e2e
  python3 $scriptdir/validate-pofiles
elif [[ "${1:-}" == "test_level" ]]; then
    python -m pytest -n 2 tests/test_level/
elif [[ "${1:-}" == "test_highlighting" ]]; then
    python -m pytest -n 2 tests/test_highlighting/
elif [[ "${1:-}" == "test_public_programs" ]]; then
    python -m pytest -n 2 tests/test_public_programs/
elif [[ "${1:-}" == "test_snippets__adventures_2-9" ]]; then
    python -m pytest -n 2 tests/test_snippets/test_adventures.py -k 'level0'
elif [[ "${1:-}" == "test_snippets__adventures_1x" ]]; then
    python -m pytest -n 2 tests/test_snippets/test_adventures.py -k 'level1'
elif [[ "${1:-}" == "test_snippets__cheatsheets" ]]; then
    python -m pytest -n 2 tests/test_snippets/test_cheatsheets.py
elif [[ "${1:-}" == "rest" ]]; then
    python -m pytest -n 2 --ignore tests/test_level --ignore tests/test_highlighting --ignore tests/test_public_programs --ignore tests/test_snippets/test_adventures.py --ignore tests/test_snippets/test_cheatsheets.py
elif [[ "${1:-}" == "--all" ]]; then # TODO this is not used
  $scriptdir/validate-tests --all
elif [[ "${1:-}" == "--weblate" ]]; then
  $scriptdir/validate-tests --weblate
else
  $scriptdir/validate-tests
fi

echo "Everything is great! 🍰"
